{% set name = "jmespath" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 472c87d80f36026ae83c6ddd0f1d05d4e510134ed462851fd5f754c8c3cbb88d

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - jmespath
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://jmespath.org/
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: Query language for JSON
  description: |
    JMESPath allows you to declaratively specify how to extract elements from
    a JSON document.
  doc_url: https://jmespath.org/tutorial.html
  dev_url: https://github.com/jmespath/jmespath.py

extra:
  recipe-maintainers:
    - pmlandwehr
