{% set name = "jmespath" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}.py/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0d602400096d7e6cf89cd52359246696b38ced8fcf992bfbdce9f04981f46864

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - jmespath
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -vv tests

about:
  home: https://jmespath.org
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Query language for JSON
  description: |
    JMESPath allows you to declaratively specify how to extract elements from
    a JSON document.
  doc_url: https://jmespath.org/tutorial.html
  dev_url: https://github.com/jmespath/jmespath.py

extra:
  recipe-maintainers:
    - pmlandwehr
