{% set name = "jmespath" %}
{% set version = "0.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b85d0567b8666149a93172712e68920734333c0ce7e89b78b3e987f71e5ed4f9

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - jmespath


about:
  home: http://jmespath.org/
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: Query language for JSON
  description: |
    JMESPath allows you to declaratively specify how to extract elements from
    a JSON document.
  doc_url: http://jmespath.org/tutorial.html
  doc_source_url: https://github.com/jmespath/jmespath.py/tree/develop/docs
  dev_url: https://github.com/jmespath/jmespath.py

extra:
  recipe-maintainers:
    - pmlandwehr
