# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kK1OYcXLF71mgszoAMAVrjIN6rs8+nrUe11+0w0sELuL2THG/aAj9Rj4lcTmD2i/C4m5xeg+79BwiSy/skfFckPn8r97sVSsr5dskd2iqutJhmZqpvr6BjXV0waQVouRHTcS3Y5BKGhllX5qZ3V4eVju5qMlUfYi4qWcs9G+06n8bfE/kN5qv7aPtlxlwgIikQ7/swTagHPtrzpms0BamLQscVVuPQ8Dj6L9CvHZRxJb0oN3sAGozgW0P0ZO6PDiCmhn5oeWmfmqBEREEjPH+EiKyodM6Sg9gGWG7rqiYWwUtbkyNkHSlG1uDUgV9wQV3gkGDcZxaeyKJdm+OXibW8ivWCFz0sOlIGYMu1sSINcnhEss4yYbTA96vLE4k7g1cWF4/6kgRpSJqeBxup8C5FXtp7xbbNDqT66zkI3j/bwPtn/sAKHI4Q82O3oeBtlt0YGg8bxdy70Q0R3ZbZApnxyHVw2dODBs7ZEl9dJphznyJfGjA3uKDEwJCLopYwyef1XwMtsVgpTYICxtabKjDOCgaNHXOOSakbxebvqa2rWsU6DODdtWeA11hll4g6OUH6vHrEHtERrZJkdHBXQhjxFLq7GFl8LqKM6dAhLIWIATXIGvqIgC+NSUiOn6cxgyS0O5ynDKDWVC5iDjIWoL49N4tOPjcvF6OqGRfabVUno="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
