# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kK1OYcXLF71mgszoAMAVrjIN6rs8+nrUe11+0w0sELuL2THG/aAj9Rj4lcTmD2i/C4m5xeg+79BwiSy/skfFckPn8r97sVSsr5dskd2iqutJhmZqpvr6BjXV0waQVouRHTcS3Y5BKGhllX5qZ3V4eVju5qMlUfYi4qWcs9G+06n8bfE/kN5qv7aPtlxlwgIikQ7/swTagHPtrzpms0BamLQscVVuPQ8Dj6L9CvHZRxJb0oN3sAGozgW0P0ZO6PDiCmhn5oeWmfmqBEREEjPH+EiKyodM6Sg9gGWG7rqiYWwUtbkyNkHSlG1uDUgV9wQV3gkGDcZxaeyKJdm+OXibW8ivWCFz0sOlIGYMu1sSINcnhEss4yYbTA96vLE4k7g1cWF4/6kgRpSJqeBxup8C5FXtp7xbbNDqT66zkI3j/bwPtn/sAKHI4Q82O3oeBtlt0YGg8bxdy70Q0R3ZbZApnxyHVw2dODBs7ZEl9dJphznyJfGjA3uKDEwJCLopYwyef1XwMtsVgpTYICxtabKjDOCgaNHXOOSakbxebvqa2rWsU6DODdtWeA11hll4g6OUH6vHrEHtERrZJkdHBXQhjxFLq7GFl8LqKM6dAhLIWIATXIGvqIgC+NSUiOn6cxgyS0O5ynDKDWVC5iDjIWoL49N4tOPjcvF6OqGRfabVUno="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
