travis:
  secure:
    BINSTAR_TOKEN: kK1OYcXLF71mgszoAMAVrjIN6rs8+nrUe11+0w0sELuL2THG/aAj9Rj4lcTmD2i/C4m5xeg+79BwiSy/skfFckPn8r97sVSsr5dskd2iqutJhmZqpvr6BjXV0waQVouRHTcS3Y5BKGhllX5qZ3V4eVju5qMlUfYi4qWcs9G+06n8bfE/kN5qv7aPtlxlwgIikQ7/swTagHPtrzpms0BamLQscVVuPQ8Dj6L9CvHZRxJb0oN3sAGozgW0P0ZO6PDiCmhn5oeWmfmqBEREEjPH+EiKyodM6Sg9gGWG7rqiYWwUtbkyNkHSlG1uDUgV9wQV3gkGDcZxaeyKJdm+OXibW8ivWCFz0sOlIGYMu1sSINcnhEss4yYbTA96vLE4k7g1cWF4/6kgRpSJqeBxup8C5FXtp7xbbNDqT66zkI3j/bwPtn/sAKHI4Q82O3oeBtlt0YGg8bxdy70Q0R3ZbZApnxyHVw2dODBs7ZEl9dJphznyJfGjA3uKDEwJCLopYwyef1XwMtsVgpTYICxtabKjDOCgaNHXOOSakbxebvqa2rWsU6DODdtWeA11hll4g6OUH6vHrEHtERrZJkdHBXQhjxFLq7GFl8LqKM6dAhLIWIATXIGvqIgC+NSUiOn6cxgyS0O5ynDKDWVC5iDjIWoL49N4tOPjcvF6OqGRfabVUno=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
